### PR TITLE
fix syntax error in README

### PR DESCRIPTION
**Pull request by gravitinos**
- should be a =

### CODE REVIEW

**Comment by garrensmith** [comment]
Awesome. Thanks for this. Have you used this library to build anything? Let me know if you have any questions or if I can help with anything.

**Comment by xvalentino** [comment]
@garrensmith thank you! Not yet but I'm looking into it, and I'll definitely let you know! This project looks awesome. Nice work!

**Comment by garrensmith** [comment]
Awesome. If you do. Let me know so I can add it to the project readme.

________________________________

**Comment by garrensmith** [comment]
@xvalentino I've created a few [issues](https://github.com/garrensmith/abletonpush/issues) that would be nice improvements. If you would be interested and have the time I would really appreciate your help with them.

**Pull request merged**
